import Link from "next/link";
import {clinic,weeklyHours,timeLabel} from "@/config/elements";
export function Logo(){return <Link href="/" className="brand" aria-label="Elements Dentistry home"><span className="brand-symbol">e<span>✦</span></span><span>elements<small>D E N T I S T R Y</small></span></Link>}
export function Header(){return <><div className="topbar"><span>Family, general & special care dentistry · Fountain Valley, CA</span><a href={`tel:${clinic.phone}`} data-track-event="call_click">{clinic.displayPhone}</a></div><header className="site-header"><Logo/><nav className="desktop-nav" aria-label="Main navigation"><Link href="/about">Our practice</Link><Link href="/services">Dental care</Link><Link href="/patient-information">For patients</Link><Link href="/contact">Visit us</Link></nav><Link href="/book-appointment" className="btn small" data-track-event="booking_click">Request a visit ↗</Link><details className="mobile-nav"><summary aria-label="Open navigation">☰</summary><nav><Link href="/about">Our practice</Link><Link href="/services">Dental care</Link><Link href="/patient-information">For patients</Link><Link href="/contact">Visit us</Link><Link href="/book-appointment">Request a visit</Link></nav></details></header></>}
export function Hours({schedule=weeklyHours}:{schedule?:Record<number,string[][]>}){return <div className="hours">{[1,2,3,4,5,6,0].map(day=><div key={day}><span>{["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"][day]}</span><span>{schedule[day]?.length?schedule[day].map(([a,b])=>`${timeLabel(a)} – ${timeLabel(b)}`).join(" / "):"Closed"}</span></div>)}<small>All hours are Pacific Time. Call for holiday availability.</small></div>}
export function CTA(){return <section className="cta wrap"><div><p className="eyebrow">YOUR NEXT CHAPTER STARTS HERE</p><h2>Let’s make your smile<br/><em>feel at home.</em></h2></div><div><Link href="/book-appointment" className="btn light" data-track-event="booking_click">Request an appointment ↗</Link><a className="text-link" href={`tel:${clinic.phone}`} data-track-event="call_click">Or call {clinic.displayPhone}</a></div></section>}
export function Footer(){return <footer className="footer wrap"><div className="footer-grid"><div><Logo/><p>Care for every smile.<br/>A place for every person.</p><p>{clinic.address}</p><a href={`tel:${clinic.phone}`} data-track-event="call_click">{clinic.displayPhone}</a></div><div><h3>Explore</h3>{[["Our dentists","/meet-our-doctors"],["Our services","/services"],["Patient information","/patient-information"],["Membership & financing","/patient-information/financing"],["Questions & answers","/faq"],["Offers","/offers"]].map(([t,h])=><Link href={h} key={h}>{t}</Link>)}</div><div><h3>Connect</h3>{Object.entries(clinic.socials).map(([t,h])=><a key={t} href={h} target="_blank" rel="noopener noreferrer" data-track-event="social_click" data-track-label={t}>{t} ↗</a>)}<Link href="/reviews">Share your experience</Link><Link href="/forms">Office forms</Link></div><div><h3>Office hours</h3><Hours/></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Elements Dentistry</span><div><Link href="/privacy">Privacy</Link><Link href="/accessibility">Accessibility</Link><Link href="/privacy#analytics">Cookie preferences</Link></div></div></footer>}
export function PageIntro({eyebrow,title,description}:{eyebrow:string;title:string;description:string}){return <section className="page-intro wrap"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="lead">{description}</p></section>}
export function Map(){return <div className="map-box"><iframe title="Elements Dentistry location in Fountain Valley" src="https://maps.google.com/maps?q=18952%20Brookhurst%20St%20Fountain%20Valley%20CA%2092708&t=&z=15&ie=UTF8&iwloc=&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade"/><a className="btn" href={clinic.map} target="_blank" rel="noopener noreferrer" data-track-event="map_click">Get directions ↗</a></div>}
